version: '2.3'
services:
    trainer:
        volumes:
            - ~/wsl/datasets:/datasets
            - ~/wsl/models:/models
        image: ${IMAGE}
        environment:
            NVIDIA_VISIBLE_DEVICES: all
            COMMAND: >
                python3 /app/wsl_survey/irn/main.py
                    --dataset_dir=/datasets/voc2007/labelled
                    --image_dir=/datasets/voc2007/data/JPEGImages
                    --checkpoints=/models/irn-voc2007
                    --voc_root=/datasets/voc2007/VOCdevkit/VOC2007/
        runtime: ${RUNTIME}
        shm_size: '8gb'
