version: '2.3'
services:
    download_dataset:
        volumes:
            - ~/wsl_data/wildcat-kitti:/datasets
        image: cenkbircanoglu/wsl-survey-gpu
        environment:
            NVIDIA_VISIBLE_DEVICES: all
            COMMAND: python3 /app/wsl_survey/datasets/kitti/download.py --dataset_dir=/datasets/kitti
        runtime: nvidia
