version: '2.3'
services:
    download_dataset:
        volumes:
            - ~/wsl/datasets:/datasets
        image: cenkbircanoglu/wsl-survey
        environment:
            COMMAND: >
                python3 /app/wsl_survey/datasets/voc/2007/download.py
                    --dataset_dir=/datasets/voc2007

    label_dataset:
        volumes:
            - ~/wsl/datasets:/datasets
        image: cenkbircanoglu/wsl-survey
        environment:
            COMMAND: >
                python3 /app/wsl_survey/datasets/voc/preprocess/labelled_dataset.py
                    --dataset_dir=/datasets/voc2007/data
                    --output_dir=/datasets/voc2007/labelled

    annotate_dataset:
        volumes:
            - ~/wsl/datasets:/datasets
        image: cenkbircanoglu/wsl-survey
        environment:
            COMMAND: >
                python3 /app/wsl_survey/datasets/voc/preprocess/annotated_dataset.py
                    --dataset_dir=/datasets/voc2007/data
                    --labelled_dir=/datasets/voc2007/labelled
                    --output_dir=/datasets/voc2007/annotated

    create_class_labels:
        volumes:
            - ~/wsl/datasets:/datasets
        image: cenkbircanoglu/wsl-survey
        environment:
            COMMAND: >
                python3 /app/wsl_survey/datasets/class_labels.py
                    --source=/datasets/voc2007/labelled
                    --target=/datasets/voc2007/labelled
